### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by lbischof** [marianoguerra/json.human.js#32]
Would it be possible to host json-human on npm? npm is also for clientside libraries and would make installing easier. You would also support node users.

**Comment by marianoguerra** [comment]
I would do it gladly, but what do I have to do? :)

**Comment by Lorenzbi** [comment]
I'm not sure. but since you're not officially supporting node and you already have a package.json you don't have to change much. https://docs.npmjs.com/getting-started/publishing-npm-packages npm automatically tags your git repository when you release a new version. https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by Lorenzbi** [comment]
maybe you can ask the author of the json-human to change his name to json-human-node. https://docs.npmjs.com/misc/disputes

**Comment by marianoguerra** [comment]
we can publish this one as json.human? or json-human-browser?

**Comment by ergo** [comment]
Hello, let me necro this a bit :)
Can we have a release? I'm migrating some legacy projects some bower and I've found this package to not live on npm.

Cheers!

**Comment by marianoguerra** [comment]
sure! would you help me? :)

what do I have to do?

**Comment by ergo** [comment]
Sure I can. So far I vendorized the dep, so it is less of a hassle for me.
You already have a package.json, so that is good, `npm pack` appears to create an archive with sources in place ;).
You have to register to NPM and follow this: https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages.

**Comment by marianoguerra** [comment]
https://www.npmjs.org/package/@marianoguerra/json-human

is that ok?

thanks for the help!

**Comment by ergo** [comment]
Hey @marianoguerra I will try test this a bit later!

**Comment by ssldhl** [comment]
Please close this issue
